name: CI/CD Pipeline   

on:
    push:
        branches:
            - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run linting
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Build Docker image
        run: docker build -t backend-app:${{ github.sha }} .

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: echo "Deploying BACKEND to PRODUCTION..."
